In [1]:
import numpy as np
import pygame
import time
import math

pygame 2.5.2 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [23]:
pygame.init()
screen = pygame.display.set_mode((400, 400))
pygame.display.set_caption('Env render test')


pygame.font.init()
font = pygame.font.Font(None, 18)


# screen.fill((255, 255, 255))
# pygame.display.update()


In [3]:
pos1 = np.array(
            [np.random.uniform(30, 370), np.random.uniform(30, 370)], dtype=np.float32)
pos2 = np.array(
            [np.random.uniform(30, 370), np.random.uniform(30, 370)], dtype=np.float32)

print(pos1)
print(pos2)

[ 81.89684 175.18796]
[277.972   296.39993]


In [4]:
angle = 0
theta  = math.radians(angle)

magnitude = 30
# ! calculating the direction vector components vec(x) and vec(y) for both points
dir_vector1_x = magnitude * math.cos(theta)
dir_vector1_y = magnitude * math.sin(theta)

dir_vector2_x = magnitude * math.cos(theta)
dir_vector2_y = magnitude * math.sin(theta)

In [18]:
dir_line_end1 = (pos1[0] + dir_vector1_x, pos1[1] + dir_vector1_y)
print(dir_line_end1)

(165.24624633789062, 40.629417419433594)


In [8]:
# the center of the circle
pos1_x, pos1_y = pos1

# converting the float32 values to int values as pygame demands it
# the center of the circle
center1 = (int(pos1_x), int(pos1_y))

pygame.draw.circle(screen, (0, 0, 255), center1, 20)

# calculating the direction endpoint from the center
dir_line_end1 = (center1[0] + dir_vector1_x, center1[1] + dir_vector1_y)
pygame.draw.line(screen, (0, 0, 255), center1, dir_line_end1, 2)


# the center of the circle
pos2_x, pos2_y = pos2
# converting the float32 values to int values as pygame demands it
# the center of the circle
center2 = (int(pos2_x), int(pos2_y))

pygame.draw.circle(screen, (255, 0, 0), center2, 20)

# calculating the direction endpoint from the center
dir_line_end2 = (center2[0] + dir_vector2_x, center2[1] + dir_vector2_y)
pygame.draw.line(screen, (255, 0, 0), center2, dir_line_end2, 2)


pygame.display.update()

In [13]:
dir_line_end1 = (center1[0] + dir_vector1_x, center1[1] + dir_vector1_y)
print(dir_line_end1)

(226.99999999999997, 373.98076211353316)


In [11]:
pos1_x, pos1_y = pos1
center1 = (int(pos1_x), int(pos1_y))
pos2_x, pos2_y = pos2
center2 = (int(pos2_x), int(pos2_y))

angle = 0

magnitude = 30

while True:
    screen.fill((255, 255, 255))

    angle += 10
    theta = math.radians(angle)
    
    dir_vector1_x = magnitude * math.cos(theta)
    dir_vector1_y = magnitude * math.sin(theta)

    dir_vector2_x = magnitude * math.cos(theta+20)
    dir_vector2_y = magnitude * math.sin(theta+20)


    dir_line_end1 = (center1[0] + dir_vector1_x, center1[1] + dir_vector1_y)
    pygame.draw.circle(screen, (0, 0, 255), center1, 15)
    pygame.draw.line(screen, (0, 0, 255), center1, dir_line_end1, 5)

    
    dir_line_end2 = (center2[0] + dir_vector2_x, center2[1] + dir_vector2_y)
    pygame.draw.line(screen, (255, 0, 0), center2, dir_line_end2, 5)
    pygame.draw.circle(screen, (255, 0, 0), center2, 15)

    

    pygame.display.update()
    pygame.time.delay(100)


KeyboardInterrupt: 

In [12]:
pygame.quit()

In [13]:
 class Agent:
    def __init__(self, agent_name, agent_index):
        self.index = agent_index
        self.agent = agent_name
        self.health = None
        self.isHit = False
        self.move = True
        self.movement_speed = 1.00
        self.previous_position = np.array([0, 0], dtype=np.float32)
        self.current_position = None
        self.same_position = False
        self.current_step = 0
        self.action = None


        self.angle = 0
        self.center = 0
        self.direction = 0
        self.direction_end = 0
        self.draw_direction_end = 0

        
        

    def agent_action(self, action):

        pass

    def agent_reset(self, width, height):
        padding = 30
        # updating the initial random position of the agent at 1st
        self.current_position = np.array(
            [np.random.uniform(30, width - padding), np.random.uniform(30, width - padding)], dtype=np.float32)

        # updating the initial orientation to 0 degree at 1st
        theta = math.radians(self.angle)
        dir_vec_x = padding * math.cos(theta)
        dir_vec_y = padding * math.sin(theta)
        self.direction_end = np.array([self.current_position[0] + dir_vec_x, self.current_position[1] + dir_vec_y ], dtype=np.float32)
        self.draw_direction_end = (self.current_position[0] + dir_vec_x, self.current_position[1] + dir_vec_y )

    def get_direction(self, angle):
        center = (int(self.current_position[0]), int(self.current_position[1]))
        self.center = center

        theta = math.radians(self.angle)
        directional_vector_x = magnitude * math.cos(theta)
        directional_vector_y = magnitude * math.sin(theta)
            
        directional_line_end = np.array([center[0] + directional_vector_x, center[1] + directional_vector_y ], dtype=np.float32)
        self.direction_end = directional_line_end

        direction = directional_line_end - center
        direction /= np.linalg.norm(direction)
        self.direction = direction
        self.draw_direction_end = (center[0] + directional_vector_x, center[1] + directional_vector_y )


        
    def step_update(self, action, range_x, range_y):
        
        # ! if used directional rotational movement
        # rotate clockwise
        if action == 0:

            self.angle += 10
            self.get_direction(self.angle)

        # rotate anti-clockwise
        elif action == 1:
            self.angle -= 10
            self.get_direction(self.angle)

        # move front
        elif action == 2:
            self.current_position = self.current_position + self.direction * self.movement_speed
            self.get_direction(self.angle)

        # move back
        elif action == 3:
            self.current_position = self.current_position - self.direction * self.movement_speed
            self.get_direction(self.angle)
            
        # do nothing / wait 
        elif action == 4:
            pass

        
        self.current_position[0] = np.clip(self.current_position[0], 0, range_x)
        self.current_position[1] = np.clip(self.current_position[1], 0, range_y)


In [14]:
agent = Agent('prey', 1)
agent.agent_reset(400, 400)

Init pos

In [15]:
agent.current_position

array([298.8917, 301.3598], dtype=float32)

Init direction end

In [16]:
agent.direction_end

array([328.8917, 301.3598], dtype=float32)

Step update

In [19]:
agent.step_update(0, 400, 400)

updated position

In [20]:
agent.angle

20

In [21]:
agent.current_position

array([298.8917, 301.3598], dtype=float32)

updated direction end

In [22]:
agent.direction_end

array([326.19077, 311.2606 ], dtype=float32)

In [32]:

agent.movement_speed = 1

while True:
    screen.fill((255, 255, 255))

    agent.step_update(4, 400, 400)

    pygame.draw.circle(screen, (0, 0, 255), agent.center, 15)
    pygame.draw.line(screen, (0, 0, 255), agent.center, agent.draw_direction_end, 5)


    pygame.display.update()
    pygame.time.delay(60)

KeyboardInterrupt: 

In [199]:
pygame.quit()