In [96]:
import numpy as np
import pygame
import time
import math
import sys

In [97]:
pygame.init()
screen = pygame.display.set_mode((400, 400))
pygame.display.set_caption('Env render test')


pygame.font.init()
font = pygame.font.Font(None, 18)


# screen.fill((255, 255, 255))
# pygame.display.update()


In [98]:
pos1 = np.array(
            [np.random.uniform(30, 370), np.random.uniform(30, 370)], dtype=np.float32)
pos2 = np.array(
            [np.random.uniform(30, 370), np.random.uniform(30, 370)], dtype=np.float32)

print(pos1)
print(pos2)

[157.91302   43.928745]
[111.13579 178.93048]


In [99]:
angle = 0
theta  = math.radians(angle)

magnitude = 30
# ! calculating the direction vector components vec(x) and vec(y) for both points
dir_vector1_x = magnitude * math.cos(theta)
dir_vector1_y = magnitude * math.sin(theta)

dir_vector2_x = magnitude * math.cos(theta)
dir_vector2_y = magnitude * math.sin(theta)

In [100]:
dir_line_end1 = (pos1[0] + dir_vector1_x, pos1[1] + dir_vector1_y)
print(dir_line_end1)

(187.91302490234375, 43.92874526977539)


In [101]:
# the center of the circle
pos1_x, pos1_y = pos1

# converting the float32 values to int values as pygame demands it
# the center of the circle
center1 = (int(pos1_x), int(pos1_y))

pygame.draw.circle(screen, (0, 0, 255), center1, 20)

# calculating the direction endpoint from the center
dir_line_end1 = (center1[0] + dir_vector1_x, center1[1] + dir_vector1_y)
pygame.draw.line(screen, (0, 0, 255), center1, dir_line_end1, 2)


# the center of the circle
pos2_x, pos2_y = pos2
# converting the float32 values to int values as pygame demands it
# the center of the circle
center2 = (int(pos2_x), int(pos2_y))

pygame.draw.circle(screen, (255, 0, 0), center2, 20)

# calculating the direction endpoint from the center
dir_line_end2 = (center2[0] + dir_vector2_x, center2[1] + dir_vector2_y)
pygame.draw.line(screen, (255, 0, 0), center2, dir_line_end2, 2)


pygame.display.update()

In [102]:
dir_line_end1 = (center1[0] + dir_vector1_x, center1[1] + dir_vector1_y)
print(dir_line_end1)

(187.0, 43.0)


In [103]:
pos1_x, pos1_y = pos1
center1 = (int(pos1_x), int(pos1_y))
pos2_x, pos2_y = pos2
center2 = (int(pos2_x), int(pos2_y))

angle = 0

magnitude = 30

while True:
    screen.fill((255, 255, 255))

    angle += 10
    theta = math.radians(angle)
    
    dir_vector1_x = magnitude * math.cos(theta)
    dir_vector1_y = magnitude * math.sin(theta)

    dir_vector2_x = magnitude * math.cos(theta+20)
    dir_vector2_y = magnitude * math.sin(theta+20)


    dir_line_end1 = (center1[0] + dir_vector1_x, center1[1] + dir_vector1_y)
    pygame.draw.circle(screen, (0, 0, 255), center1, 15)
    pygame.draw.line(screen, (0, 0, 255), center1, dir_line_end1, 5)

    
    dir_line_end2 = (center2[0] + dir_vector2_x, center2[1] + dir_vector2_y)
    pygame.draw.line(screen, (255, 0, 0), center2, dir_line_end2, 5)
    pygame.draw.circle(screen, (255, 0, 0), center2, 15)

    

    pygame.display.update()
    pygame.time.delay(100)


KeyboardInterrupt: 

In [ ]:
pygame.quit()

In [120]:
 class Agent:
    def __init__(self, agent_name, agent_index):
        self.index = agent_index
        self.agent = agent_name
        self.health = None
        self.isHit = False
        self.move = True
        self.movement_speed = 1.00
        self.previous_position = np.array([0, 0], dtype=np.float32)
        self.current_position = None
        self.same_position = False
        self.current_step = 0
        self.action = None
        self.radius = 10


        self.angle = 0
        self.center = 0
        self.direction = 0
        self.direction_end = 0
        self.draw_direction_end = 0

        
        

    def agent_action(self, action):

        pass

    def agent_reset(self, width, height):
        padding = 30
        # updating the initial random position of the agent at 1st
        self.current_position = np.array(
            [np.random.uniform(30, width - padding), np.random.uniform(30, width - padding)], dtype=np.float32)

        center = (int(self.current_position[0]), int(self.current_position[1]))
        self.center = center

        # updating the initial orientation to 0 degree at 1st
        theta = math.radians(self.angle)
        dir_vec_x = padding * math.cos(theta)
        dir_vec_y = padding * math.sin(theta)
        self.direction_end = np.array([self.current_position[0] + dir_vec_x, self.current_position[1] + dir_vec_y ], dtype=np.float32)
        self.draw_direction_end = (self.current_position[0] + dir_vec_x, self.current_position[1] + dir_vec_y )

    def get_direction(self, angle):
        center = (int(self.current_position[0]), int(self.current_position[1]))
        self.center = center

        theta = math.radians(self.angle)
        magnitude = 30
        directional_vector_x = magnitude * math.cos(theta)
        directional_vector_y = magnitude * math.sin(theta)
            
        directional_line_end = np.array([center[0] + directional_vector_x, center[1] + directional_vector_y ], dtype=np.float32)
        self.direction_end = directional_line_end

        direction = directional_line_end - center
        direction /= np.linalg.norm(direction)
        self.direction = direction
        self.draw_direction_end = (center[0] + directional_vector_x, center[1] + directional_vector_y )


        
    def step_update(self, action, range_x, range_y):
        
        # ! if used directional rotational movement
        # rotate clockwise
        if action == 0:

            self.angle += 10
            self.angle = self.angle % 360
            self.get_direction(self.angle)

        # rotate anti-clockwise
        elif action == 1:
            self.angle -= 10
            self.angle = self.angle % 360
            self.get_direction(self.angle)

        # move front
        elif action == 2:
            self.current_position = self.current_position + self.direction * self.movement_speed
            self.get_direction(self.angle)

        # move back
        elif action == 3:
            self.current_position = self.current_position - self.direction * self.movement_speed
            self.get_direction(self.angle)
            
        # do nothing / wait 
        elif action == 4:
            pass

        
        self.current_position[0] = np.clip(self.current_position[0], 0, range_x)
        self.current_position[1] = np.clip(self.current_position[1], 0, range_y)


In [121]:
agent = Agent('prey', 1)
agent.agent_reset(400, 400)

Init pos

In [ ]:
agent.center

(109, 159)

Init direction end

In [ ]:
agent.direction_end

array([107.287636,  80.56996 ], dtype=float32)

Step update

In [ ]:
agent.step_update(0, 400, 400)

updated position

In [ ]:
agent.angle

20

In [ ]:
agent.current_position

array([298.8917, 301.3598], dtype=float32)

updated direction end

In [ ]:
agent.direction_end

array([326.19077, 311.2606 ], dtype=float32)

In [ ]:

agent.movement_speed = 1

while True:
    screen.fill((255, 255, 255))

    agent.step_update(4, 400, 400)

    pygame.draw.circle(screen, (0, 0, 255), agent.center, 15)
    pygame.draw.line(screen, (0, 0, 255), agent.center, agent.draw_direction_end, 5)


    pygame.display.update()
    pygame.time.delay(60)

TypeError: center argument must be a pair of numbers

In [104]:
pygame.quit()

In [108]:
def draw_wall(x, y, width, height):
    wall = pygame.Rect(x, y, width, height)
    return wall

In [175]:
wall1 = draw_wall(300, 100, 20, 200)
wall2 = draw_wall(100, 200, 50, 20)

walls = [wall1, wall2]


In [110]:
wall1.right

320

In [177]:
pygame.init()
screen = pygame.display.set_mode((400, 400))
pygame.display.set_caption('Env render test')


pygame.font.init()
font = pygame.font.Font(None, 18)

In [176]:
agent.agent_reset(400, 400)
agent.radius = 15

In [113]:
valid_x = (0, 400)
valid_y = (0, 400)

In [180]:
running = True
agent.movement_speed = 0.5
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False


    keys = pygame.key.get_pressed()
    
    if keys[pygame.K_LEFT]:
        agent.step_update(1, 400, 400)
    if keys[pygame.K_RIGHT]:
        agent.step_update(0, 400, 400)
    if keys[pygame.K_UP]:
        agent.step_update(2, 400, 400)
    if keys[pygame.K_DOWN]:
        agent.step_update(3, 400, 400)

    
    """
    this part here handles all the side collision of the walls
    """
    offset = 9
    for wall in walls:
        if agent.current_position[0] + agent.radius > wall.left and agent.current_position[0] < wall.right:
            if wall.top - offset < agent.current_position[1] < wall.bottom + offset:
                agent.current_position[0] = wall.left - agent.radius 
                print('collision with left wall')

        if agent.current_position[0] - agent.radius < wall.right and agent.current_position[0] > wall.left:
            if wall.top - offset < agent.current_position[1] < wall.bottom + offset:
                agent.current_position[0] = wall.right + agent.radius 
                print('Collision with right wall')

        if agent.current_position[1] + agent.radius > wall.top and agent.current_position[1] < wall.bottom:
            if wall.left - offset < agent.current_position[0] < wall.right + offset:
                agent.current_position[1] = wall.top - agent.radius
                print('Collision with top wall')

        if agent.current_position[1] - agent.radius < wall.bottom and agent.current_position[1] > wall.top:
            if wall.left - offset < agent.current_position[0] < wall.right + offset:
                agent.current_position[1] = wall.bottom + agent.radius
                print('Collision with bottom wall')
    
    """
    this part here handles all the corner collision of the walls
    """

    # agent.current_position = np.array([agent.current_position[0], agent.current_position[1]], dtype=np.float32)
    # agent.get_direction(agent.angle)
    
    screen.fill((255, 255, 255))

    for wall in walls:
        pygame.draw.rect(screen, (0, 0, 0), wall)

    
    pygame.draw.circle(screen, (0, 0, 255), agent.center, agent.radius)
    pygame.draw.line(screen, (0, 0, 255), agent.center, agent.draw_direction_end, 5)

    # pygame.display.update()
    pygame.display.flip()
    pygame.time.delay(20)
    print(f'agent: {agent.current_position} wall: left:{wall1.left}, right:{wall1.right}, top:{wall1.top}, bottom:{wall1.bottom}')
    print(agent.angle)

pygame.quit()


agent: [113.7912418  151.80172601] wall: left:300, right:320, top:100, bottom:300
80
